services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel_management_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_management
    ports:
      - '5432:5432'
    volumes:
      - hotel_pg_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: hotel_management_mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  hotel_pg_data:
